// Generated by Haxe 4.0.5
(function ($global) { "use strict";
function $extend(from, fields) {
	var proto = Object.create(from);
	for (var name in fields) proto[name] = fields[name];
	if( fields.toString !== Object.prototype.toString ) proto.toString = fields.toString;
	return proto;
}
var basics_Main = function() {
	var _gthis = this;
	var options = { width : window.innerWidth, height : window.innerHeight, backgroundColor : 26214, transparent : true, antialias : false};
	PIXI.Application.call(this,options);
	this.ticker.add(function(delta) {
		_gthis._animate(delta);
	});
	this._bunny = new PIXI.Sprite(PIXI.Texture.from("assets/basics/bunny.png"));
	this._bunny.anchor.set(0.5);
	this._bunny.position.set(400,300);
	this._graphic = new PIXI.Graphics();
	this._graphic.beginFill(16711680,0.4);
	this._graphic.drawRect(200,150,400,300);
	this._graphic.endFill();
	this.stage.addChild(this._graphic);
	this.stage.addChild(this._bunny);
};
basics_Main.main = function() {
	new basics_Main();
};
basics_Main.__super__ = PIXI.Application;
basics_Main.prototype = $extend(PIXI.Application.prototype,{
	_animate: function(e) {
		this._bunny.rotation += 0.1;
	}
});
var haxe_io_Bytes = function() { };
basics_Main.main();
})({});

//# sourceMappingURL=basics.js.map